// LesMills class codes.
export const CLASS_CODES = {
    6:  "BodyAttack 45",
    7:  "BodyBalance",
    9:  "BodyBalance 45",
    11: "BodyCombat",
    13: "BodyCombat 45",
    14: "BodyJam",
    17: "BodyPump",
    18: "BodyPump 30",
    19: "BodyPump 45",
    20: "BodyStep",
    22: "BodyStep 45",
    26: "CXWORX",
    29: "Grit Athletic",
    30: "GRIT Cardio",
    32: "GRIT Strength",
    34: "Impact",
    42: "Sh'Bam",
    45: "The Trip",
    46: "Tone",
    50: "Virtual BodyBalance",
    53: "Virtual CXWORX",
    54: "Virtual GRIT Cardio",
    56: "Virtual GRIT Strength",
    57: "Virtual RPM",
    59: "Yoga",
    60: "Sprint",
    61: "RPM",
    63: "Virtual Barre",
    64: "Virtual Sprint",
    65: "Virtual The Trip",
    95: "Virtual BodyPump 30",
    97: "Virtual BodyCombat 30",
    100: "Virtual BodyBalance 30",
    135: "RPM Enduro",
    955: "Virtual GRIT Athletic",
};